version: "2.4"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: $PIHOLE_TIMEZONE
      WEBPASSWORD: $PIHOLE_WEBPASSWORD
      ServerIP: $PIHOLE_SERVERIP
      DNS1: "172.16.238.10#5353"
      DNS2: "172.16.238.10#5353"
    # Volumes store your data between container upgrades
    volumes:
      - '$PIHOLE_CONFDIR:/etc/pihole/'
      - '$DNSMASQ_CONFDIR:/etc/dnsmasq.d/'
      # run `touch ./var-log/pihole.log` first unless you like errors
      # - './var-log/pihole.log:/var/log/pihole.log'
    # Need a fallback dns server
    dns:
      - 127.0.0.1
    networks:
      - dns
      - default
    restart: unless-stopped
    depends_on: 
      - stubby

  stubby:
    container_name: stubby
    image: iurimieras/stubby_armv7:latest
    expose:
      - "5353/udp"
    networks:
      dns:
        ipv4_address: 172.16.238.10
    restart: unless-stopped

  pihole-exporter:
    container_name: pihole-exporter
    image: ekofr/pihole-exporter:0.0.9
    environment:
      PIHOLE_HOSTNAME: "pihole"
      PIHOLE_PASSWORD: $PIHOLE_WEBPASSWORD
      INTERVAL: "30s"
      PORT: 9617
    ports:
        - "9617:9617"
    depends_on: 
      - pihole
    restart: unless-stopped

networks:
  dns:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1